# Import Library | pandas | numpy

In [1]:
import numpy as np
import pandas as pd

#  Import Datasets

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
14   15    Male     Poor        PG       Yes
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
44   77  Female  Average        UG        No
35   74    Male     Poor    School       Yes

# Eliminate Unnecessary Columns

In [4]:
df = df.iloc[:,2:]

In [5]:
df.sample(5)

review education purchased
13  Average    School        No
46     Poor        PG        No
40     Good    School        No
6      Good    School        No
26     Poor        PG        No

# Train_Test_Split

In [6]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1:],test_size=0.2) 

# Import_OrdinalEncoder

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
x_train

review education
5   Average    School
35     Poor    School
48     Good        UG
45     Poor        PG
23     Good    School
37  Average        PG
33     Good        PG
49     Good        UG
28     Poor    School
30  Average        UG
4   Average        UG
10     Good        UG
38     Good    School
3      Good        PG
31     Poor    School
1      Poor        UG
7      Poor    School
43     Poor        PG
13  Average    School
9      Good        UG
32  Average        UG
16     Poor        UG
17     Poor        UG
26     Poor        PG
39     Poor        PG
19     Poor        PG
41     Good        PG
8   Average        UG
0   Average    School
46     Poor        PG
25     Good    School
2      Good        PG
24  Average        PG
6      Good    School
11     Good        UG
40     Good    School
47     Good        PG
20  Average    School
42     Good        PG
34  Average    School

# Define Categories

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

# Transform Ordinal Encoding

In [10]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [11]:
x_train

array([[1., 0.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 0.]])

In [12]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

#  Label Encoding

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

In [15]:
le.fit(y_train)

C:\Users\Pratik\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [16]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [18]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

C:\Users\Pratik\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\Pratik\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [19]:
y_train

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0])

#  Import Library | pandas | numpy

In [21]:
import numpy as np
import pandas as pd

# Import Datasets

In [22]:
df = pd.read_csv('cars.csv')
df.sample(5)

brand  km_driven    fuel         owner  selling_price
11       Maruti     100000  Petrol  Second Owner          92000
7253  Chevrolet      70000  Diesel  Second Owner         165000
7668     Maruti      89000  Diesel  Second Owner         250000
332      Nissan      50000  Diesel   First Owner         250000
6308   Mahindra      30000  Diesel   First Owner        1500000

In [23]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [24]:
df['brand'].value_counts()
df['brand'].nunique()

32

In [25]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

#  1. One Hot Encoding Using Pandas

In [26]:
pd.get_dummies(df,columns=['fuel','owner'])

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000     False         True     False   
1       Skoda     120000         370000     False         True     False   
2       Honda     140000         158000     False        False     False   
3     Hyundai     127000         225000     False         True     False   
4      Maruti     120000         130000     False        False     False   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000     False        False     False   
8124  Hyundai     119000         135000     False         True     False   
8125   Maruti     120000         382000     False         True     False   
8126     Tata      25000         290000     False         True     False   
8127     Tata      25000         290000     False         True     False   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0           False               True                       False   
1           False              False                       False   
2            True              False                       False   
3           False               True                       False   
4            True               True                       False   
...           ...                ...                         ...   
8123         True               True                       False   
8124        False              False                        True   
8125        False               True                       False   
8126        False               True                       False   
8127        False               True                       False   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                  False                 False              False  
1                   True                 False              False  
2                  False                 False               True  
3                  False                 False              False  
4                  False                 False              False  
...                  ...                   ...                ...  
8123               False                 False              False  
8124               False                 False              False  
8125               False                 False              False  
8126               False                 False              False  
8127               False                 False              False  

[8128 rows x 12 columns]

#  2. K-1 One Hot Encoding

In [27]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000         True     False        False   
1       Skoda     120000         370000         True     False        False   
2       Honda     140000         158000        False     False         True   
3     Hyundai     127000         225000         True     False        False   
4      Maruti     120000         130000        False     False         True   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000        False     False         True   
8124  Hyundai     119000         135000         True     False        False   
8125   Maruti     120000         382000         True     False        False   
8126     Tata      25000         290000         True     False        False   
8127     Tata      25000         290000         True     False        False   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                          False               False                 False   
1                          False                True                 False   
2                          False               False                 False   
3                          False               False                 False   
4                          False               False                 False   
...                          ...                 ...                   ...   
8123                       False               False                 False   
8124                        True               False                 False   
8125                       False               False                 False   
8126                       False               False                 False   
8127                       False               False                 False   

      owner_Third Owner  
0                 False  
1                 False  
2                  True  
3                 False  
4                 False  
...                 ...  
8123              False  
8124              False  
8125              False  
8126              False  
8127              False  

[8128 rows x 10 columns]

#  3. One hot encoding Using Sklearn

In [28]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [29]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [30]:
X_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [31]:
X_test.head()

brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

#  Import OHE: SK Learn

In [48]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

# Use sparse_output instead of sparse
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [51]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [53]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [54]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [55]:
X_train_new.shape

(8128, 7)

In [61]:
np.hstack((X_train[['fuel','owner']].values, X_train_new))

array([['Diesel', 'First Owner', 1, ..., 0, 0, 0],
       ['Diesel', 'Second Owner', 1, ..., 1, 0, 0],
       ['Petrol', 'Third Owner', 0, ..., 0, 0, 1],
       ...,
       ['Diesel', 'First Owner', 1, ..., 0, 0, 0],
       ['Diesel', 'First Owner', 1, ..., 0, 0, 0],
       ['Diesel', 'First Owner', 1, ..., 0, 0, 0]], dtype=object)